#!/bin/bash

mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $TEST_DB CHARACTER SET utf8 COLLATE utf8_general_ci";
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE USER $TEST_USER@'%' IDENTIFIED BY '$MYSQL_PASSWORD'";
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $TEST_DB.* TO '$TEST_USER'@'%';"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

